version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: php_app
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    ports:
      - "9000:9000" # PHP-FPM listens on port 9000
    networks:
      - app-network

  web:
    image: nginx:latest
    container_name: nginx_web
    volumes:
      - ./app:/var/www/html
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
